apiVersion: v1
kind: Service
metadata:
  name: graylog
  labels:
    name: graylog
    app: {{ template "graylog.name" . }}
    chart: {{ template "graylog.chart" . }}
    component: graylog-service
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    graylog: "true"
  ports:
  - name: http
    protocol: TCP
    port: 9000
    nodePort: 31300
  - name: udp-input
    protocol: UDP
    port: 12201
    nodePort: 31301
  - name: tcp-input
    protocol: TCP
    port: 1514
    nodePort: 31302
  type: NodePort
